/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AccountRouteImport } from './routes/account'
import { Route as CheckoutRouteImport } from './routes/checkout'
import { Route as HqRouteImport } from './routes/hq'
import { Route as LoginRouteImport } from './routes/login'
import { Route as PackagesRouteImport } from './routes/packages'
import { Route as PrivacyRouteImport } from './routes/privacy'
import { Route as ReceptionistRouteImport } from './routes/receptionist'
import { Route as ServicesRouteImport } from './routes/services'
import { Route as StartRouteImport } from './routes/start'
import { Route as TermsRouteImport } from './routes/terms'
import { Route as WorkRouteImport } from './routes/work'
import { Route as AccountIndexRouteImport } from './routes/account.index'
import { Route as DepartmentsIdRouteImport } from './routes/departments.$id'
import { Route as HqIndexRouteImport } from './routes/hq/index'
import { Route as HqAssistantsRouteImport } from './routes/hq/assistants'
import { Route as HqCatalogRouteImport } from './routes/hq/catalog'
import { Route as HqClientsRouteImport } from './routes/hq/clients'
import { Route as HqDemoRouteImport } from './routes/hq/demo'
import { Route as HqInboxRouteImport } from './routes/hq/inbox'
import { Route as HqInquiriesRouteImport } from './routes/hq/inquiries'
import { Route as HqLegalRouteImport } from './routes/hq/legal'
import { Route as HqPagesRouteImport } from './routes/hq/pages'
import { Route as HqPaymentsRouteImport } from './routes/hq/payments'
import { Route as HqProjectsRouteImport } from './routes/hq/projects'
import { Route as HqQualityRouteImport } from './routes/hq/quality'
import { Route as HqTeamRouteImport } from './routes/hq/team'
import { Route as OffersIndexRouteImport } from './routes/offers.index'
import { Route as OffersSlugRouteImport } from './routes/offers.$slug'
import { Route as AccountOrdersIdRouteImport } from './routes/account.orders.$id'
import { Route as ApiAuthSplatRouteImport } from './routes/api/auth/$'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AccountRoute = AccountRouteImport.update({
  id: '/account',
  path: '/account',
  getParentRoute: () => rootRouteImport,
} as any)
const CheckoutRoute = CheckoutRouteImport.update({
  id: '/checkout',
  path: '/checkout',
  getParentRoute: () => rootRouteImport,
} as any)
const HqRoute = HqRouteImport.update({
  id: '/hq',
  path: '/hq',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const PackagesRoute = PackagesRouteImport.update({
  id: '/packages',
  path: '/packages',
  getParentRoute: () => rootRouteImport,
} as any)
const PrivacyRoute = PrivacyRouteImport.update({
  id: '/privacy',
  path: '/privacy',
  getParentRoute: () => rootRouteImport,
} as any)
const ReceptionistRoute = ReceptionistRouteImport.update({
  id: '/receptionist',
  path: '/receptionist',
  getParentRoute: () => rootRouteImport,
} as any)
const ServicesRoute = ServicesRouteImport.update({
  id: '/services',
  path: '/services',
  getParentRoute: () => rootRouteImport,
} as any)
const StartRoute = StartRouteImport.update({
  id: '/start',
  path: '/start',
  getParentRoute: () => rootRouteImport,
} as any)
const TermsRoute = TermsRouteImport.update({
  id: '/terms',
  path: '/terms',
  getParentRoute: () => rootRouteImport,
} as any)
const WorkRoute = WorkRouteImport.update({
  id: '/work',
  path: '/work',
  getParentRoute: () => rootRouteImport,
} as any)
const AccountIndexRoute = AccountIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AccountRoute,
} as any)
const DepartmentsIdRoute = DepartmentsIdRouteImport.update({
  id: '/departments/$id',
  path: '/departments/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const HqIndexRoute = HqIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => HqRoute,
} as any)
const HqAssistantsRoute = HqAssistantsRouteImport.update({
  id: '/assistants',
  path: '/assistants',
  getParentRoute: () => HqRoute,
} as any)
const HqCatalogRoute = HqCatalogRouteImport.update({
  id: '/catalog',
  path: '/catalog',
  getParentRoute: () => HqRoute,
} as any)
const HqClientsRoute = HqClientsRouteImport.update({
  id: '/clients',
  path: '/clients',
  getParentRoute: () => HqRoute,
} as any)
const HqDemoRoute = HqDemoRouteImport.update({
  id: '/demo',
  path: '/demo',
  getParentRoute: () => HqRoute,
} as any)
const HqInboxRoute = HqInboxRouteImport.update({
  id: '/inbox',
  path: '/inbox',
  getParentRoute: () => HqRoute,
} as any)
const HqInquiriesRoute = HqInquiriesRouteImport.update({
  id: '/inquiries',
  path: '/inquiries',
  getParentRoute: () => HqRoute,
} as any)
const HqLegalRoute = HqLegalRouteImport.update({
  id: '/legal',
  path: '/legal',
  getParentRoute: () => HqRoute,
} as any)
const HqPagesRoute = HqPagesRouteImport.update({
  id: '/pages',
  path: '/pages',
  getParentRoute: () => HqRoute,
} as any)
const HqPaymentsRoute = HqPaymentsRouteImport.update({
  id: '/payments',
  path: '/payments',
  getParentRoute: () => HqRoute,
} as any)
const HqProjectsRoute = HqProjectsRouteImport.update({
  id: '/projects',
  path: '/projects',
  getParentRoute: () => HqRoute,
} as any)
const HqQualityRoute = HqQualityRouteImport.update({
  id: '/quality',
  path: '/quality',
  getParentRoute: () => HqRoute,
} as any)
const HqTeamRoute = HqTeamRouteImport.update({
  id: '/team',
  path: '/team',
  getParentRoute: () => HqRoute,
} as any)
const OffersIndexRoute = OffersIndexRouteImport.update({
  id: '/offers/',
  path: '/offers/',
  getParentRoute: () => rootRouteImport,
} as any)
const OffersSlugRoute = OffersSlugRouteImport.update({
  id: '/offers/$slug',
  path: '/offers/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const AccountOrdersIdRoute = AccountOrdersIdRouteImport.update({
  id: '/orders/$id',
  path: '/orders/$id',
  getParentRoute: () => AccountRoute,
} as any)
const ApiAuthSplatRoute = ApiAuthSplatRouteImport.update({
  id: '/api/auth/$',
  path: '/api/auth/$',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/account': typeof AccountRouteWithChildren
  '/checkout': typeof CheckoutRoute
  '/hq': typeof HqRouteWithChildren
  '/login': typeof LoginRoute
  '/packages': typeof PackagesRoute
  '/privacy': typeof PrivacyRoute
  '/receptionist': typeof ReceptionistRoute
  '/services': typeof ServicesRoute
  '/start': typeof StartRoute
  '/terms': typeof TermsRoute
  '/work': typeof WorkRoute
  '/departments/$id': typeof DepartmentsIdRoute
  '/hq/assistants': typeof HqAssistantsRoute
  '/hq/catalog': typeof HqCatalogRoute
  '/hq/clients': typeof HqClientsRoute
  '/hq/demo': typeof HqDemoRoute
  '/hq/inbox': typeof HqInboxRoute
  '/hq/inquiries': typeof HqInquiriesRoute
  '/hq/legal': typeof HqLegalRoute
  '/hq/pages': typeof HqPagesRoute
  '/hq/payments': typeof HqPaymentsRoute
  '/hq/projects': typeof HqProjectsRoute
  '/hq/quality': typeof HqQualityRoute
  '/hq/team': typeof HqTeamRoute
  '/offers/$slug': typeof OffersSlugRoute
  '/account/': typeof AccountIndexRoute
  '/hq/': typeof HqIndexRoute
  '/offers/': typeof OffersIndexRoute
  '/account/orders/$id': typeof AccountOrdersIdRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/checkout': typeof CheckoutRoute
  '/login': typeof LoginRoute
  '/packages': typeof PackagesRoute
  '/privacy': typeof PrivacyRoute
  '/receptionist': typeof ReceptionistRoute
  '/services': typeof ServicesRoute
  '/start': typeof StartRoute
  '/terms': typeof TermsRoute
  '/work': typeof WorkRoute
  '/departments/$id': typeof DepartmentsIdRoute
  '/hq/assistants': typeof HqAssistantsRoute
  '/hq/catalog': typeof HqCatalogRoute
  '/hq/clients': typeof HqClientsRoute
  '/hq/demo': typeof HqDemoRoute
  '/hq/inbox': typeof HqInboxRoute
  '/hq/inquiries': typeof HqInquiriesRoute
  '/hq/legal': typeof HqLegalRoute
  '/hq/pages': typeof HqPagesRoute
  '/hq/payments': typeof HqPaymentsRoute
  '/hq/projects': typeof HqProjectsRoute
  '/hq/quality': typeof HqQualityRoute
  '/hq/team': typeof HqTeamRoute
  '/offers/$slug': typeof OffersSlugRoute
  '/account': typeof AccountIndexRoute
  '/hq': typeof HqIndexRoute
  '/offers': typeof OffersIndexRoute
  '/account/orders/$id': typeof AccountOrdersIdRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/account': typeof AccountRouteWithChildren
  '/checkout': typeof CheckoutRoute
  '/hq': typeof HqRouteWithChildren
  '/login': typeof LoginRoute
  '/packages': typeof PackagesRoute
  '/privacy': typeof PrivacyRoute
  '/receptionist': typeof ReceptionistRoute
  '/services': typeof ServicesRoute
  '/start': typeof StartRoute
  '/terms': typeof TermsRoute
  '/work': typeof WorkRoute
  '/departments/$id': typeof DepartmentsIdRoute
  '/hq/assistants': typeof HqAssistantsRoute
  '/hq/catalog': typeof HqCatalogRoute
  '/hq/clients': typeof HqClientsRoute
  '/hq/demo': typeof HqDemoRoute
  '/hq/inbox': typeof HqInboxRoute
  '/hq/inquiries': typeof HqInquiriesRoute
  '/hq/legal': typeof HqLegalRoute
  '/hq/pages': typeof HqPagesRoute
  '/hq/payments': typeof HqPaymentsRoute
  '/hq/projects': typeof HqProjectsRoute
  '/hq/quality': typeof HqQualityRoute
  '/hq/team': typeof HqTeamRoute
  '/offers/$slug': typeof OffersSlugRoute
  '/account/': typeof AccountIndexRoute
  '/hq/': typeof HqIndexRoute
  '/offers/': typeof OffersIndexRoute
  '/account/orders/$id': typeof AccountOrdersIdRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/account'
    | '/checkout'
    | '/hq'
    | '/login'
    | '/packages'
    | '/privacy'
    | '/receptionist'
    | '/services'
    | '/start'
    | '/terms'
    | '/work'
    | '/departments/$id'
    | '/hq/assistants'
    | '/hq/catalog'
    | '/hq/clients'
    | '/hq/demo'
    | '/hq/inbox'
    | '/hq/inquiries'
    | '/hq/legal'
    | '/hq/pages'
    | '/hq/payments'
    | '/hq/projects'
    | '/hq/quality'
    | '/hq/team'
    | '/offers/$slug'
    | '/account/'
    | '/hq/'
    | '/offers/'
    | '/account/orders/$id'
    | '/api/auth/$'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/checkout'
    | '/login'
    | '/packages'
    | '/privacy'
    | '/receptionist'
    | '/services'
    | '/start'
    | '/terms'
    | '/work'
    | '/departments/$id'
    | '/hq/assistants'
    | '/hq/catalog'
    | '/hq/clients'
    | '/hq/demo'
    | '/hq/inbox'
    | '/hq/inquiries'
    | '/hq/legal'
    | '/hq/pages'
    | '/hq/payments'
    | '/hq/projects'
    | '/hq/quality'
    | '/hq/team'
    | '/offers/$slug'
    | '/account'
    | '/hq'
    | '/offers'
    | '/account/orders/$id'
    | '/api/auth/$'
  id:
    | '__root__'
    | '/'
    | '/account'
    | '/checkout'
    | '/hq'
    | '/login'
    | '/packages'
    | '/privacy'
    | '/receptionist'
    | '/services'
    | '/start'
    | '/terms'
    | '/work'
    | '/departments/$id'
    | '/hq/assistants'
    | '/hq/catalog'
    | '/hq/clients'
    | '/hq/demo'
    | '/hq/inbox'
    | '/hq/inquiries'
    | '/hq/legal'
    | '/hq/pages'
    | '/hq/payments'
    | '/hq/projects'
    | '/hq/quality'
    | '/hq/team'
    | '/offers/$slug'
    | '/account/'
    | '/hq/'
    | '/offers/'
    | '/account/orders/$id'
    | '/api/auth/$'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AccountRoute: typeof AccountRouteWithChildren
  CheckoutRoute: typeof CheckoutRoute
  HqRoute: typeof HqRouteWithChildren
  LoginRoute: typeof LoginRoute
  PackagesRoute: typeof PackagesRoute
  PrivacyRoute: typeof PrivacyRoute
  ReceptionistRoute: typeof ReceptionistRoute
  ServicesRoute: typeof ServicesRoute
  StartRoute: typeof StartRoute
  TermsRoute: typeof TermsRoute
  WorkRoute: typeof WorkRoute
  DepartmentsIdRoute: typeof DepartmentsIdRoute
  OffersSlugRoute: typeof OffersSlugRoute
  OffersIndexRoute: typeof OffersIndexRoute
  ApiAuthSplatRoute: typeof ApiAuthSplatRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/account': {
      id: '/account'
      path: '/account'
      fullPath: '/account'
      preLoaderRoute: typeof AccountRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/checkout': {
      id: '/checkout'
      path: '/checkout'
      fullPath: '/checkout'
      preLoaderRoute: typeof CheckoutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/hq': {
      id: '/hq'
      path: '/hq'
      fullPath: '/hq'
      preLoaderRoute: typeof HqRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/packages': {
      id: '/packages'
      path: '/packages'
      fullPath: '/packages'
      preLoaderRoute: typeof PackagesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/privacy': {
      id: '/privacy'
      path: '/privacy'
      fullPath: '/privacy'
      preLoaderRoute: typeof PrivacyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/receptionist': {
      id: '/receptionist'
      path: '/receptionist'
      fullPath: '/receptionist'
      preLoaderRoute: typeof ReceptionistRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/services': {
      id: '/services'
      path: '/services'
      fullPath: '/services'
      preLoaderRoute: typeof ServicesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/start': {
      id: '/start'
      path: '/start'
      fullPath: '/start'
      preLoaderRoute: typeof StartRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/terms': {
      id: '/terms'
      path: '/terms'
      fullPath: '/terms'
      preLoaderRoute: typeof TermsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/work': {
      id: '/work'
      path: '/work'
      fullPath: '/work'
      preLoaderRoute: typeof WorkRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/account/': {
      id: '/account/'
      path: '/'
      fullPath: '/account/'
      preLoaderRoute: typeof AccountIndexRouteImport
      parentRoute: typeof AccountRoute
    }
    '/departments/$id': {
      id: '/departments/$id'
      path: '/departments/$id'
      fullPath: '/departments/$id'
      preLoaderRoute: typeof DepartmentsIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/hq/': {
      id: '/hq/'
      path: '/'
      fullPath: '/hq/'
      preLoaderRoute: typeof HqIndexRouteImport
      parentRoute: typeof HqRoute
    }
    '/hq/assistants': {
      id: '/hq/assistants'
      path: '/assistants'
      fullPath: '/hq/assistants'
      preLoaderRoute: typeof HqAssistantsRouteImport
      parentRoute: typeof HqRoute
    }
    '/hq/catalog': {
      id: '/hq/catalog'
      path: '/catalog'
      fullPath: '/hq/catalog'
      preLoaderRoute: typeof HqCatalogRouteImport
      parentRoute: typeof HqRoute
    }
    '/hq/clients': {
      id: '/hq/clients'
      path: '/clients'
      fullPath: '/hq/clients'
      preLoaderRoute: typeof HqClientsRouteImport
      parentRoute: typeof HqRoute
    }
    '/hq/demo': {
      id: '/hq/demo'
      path: '/demo'
      fullPath: '/hq/demo'
      preLoaderRoute: typeof HqDemoRouteImport
      parentRoute: typeof HqRoute
    }
    '/hq/inbox': {
      id: '/hq/inbox'
      path: '/inbox'
      fullPath: '/hq/inbox'
      preLoaderRoute: typeof HqInboxRouteImport
      parentRoute: typeof HqRoute
    }
    '/hq/inquiries': {
      id: '/hq/inquiries'
      path: '/inquiries'
      fullPath: '/hq/inquiries'
      preLoaderRoute: typeof HqInquiriesRouteImport
      parentRoute: typeof HqRoute
    }
    '/hq/legal': {
      id: '/hq/legal'
      path: '/legal'
      fullPath: '/hq/legal'
      preLoaderRoute: typeof HqLegalRouteImport
      parentRoute: typeof HqRoute
    }
    '/hq/pages': {
      id: '/hq/pages'
      path: '/pages'
      fullPath: '/hq/pages'
      preLoaderRoute: typeof HqPagesRouteImport
      parentRoute: typeof HqRoute
    }
    '/hq/payments': {
      id: '/hq/payments'
      path: '/payments'
      fullPath: '/hq/payments'
      preLoaderRoute: typeof HqPaymentsRouteImport
      parentRoute: typeof HqRoute
    }
    '/hq/projects': {
      id: '/hq/projects'
      path: '/projects'
      fullPath: '/hq/projects'
      preLoaderRoute: typeof HqProjectsRouteImport
      parentRoute: typeof HqRoute
    }
    '/hq/quality': {
      id: '/hq/quality'
      path: '/quality'
      fullPath: '/hq/quality'
      preLoaderRoute: typeof HqQualityRouteImport
      parentRoute: typeof HqRoute
    }
    '/hq/team': {
      id: '/hq/team'
      path: '/team'
      fullPath: '/hq/team'
      preLoaderRoute: typeof HqTeamRouteImport
      parentRoute: typeof HqRoute
    }
    '/offers/': {
      id: '/offers/'
      path: '/offers'
      fullPath: '/offers/'
      preLoaderRoute: typeof OffersIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/offers/$slug': {
      id: '/offers/$slug'
      path: '/offers/$slug'
      fullPath: '/offers/$slug'
      preLoaderRoute: typeof OffersSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/account/orders/$id': {
      id: '/account/orders/$id'
      path: '/orders/$id'
      fullPath: '/account/orders/$id'
      preLoaderRoute: typeof AccountOrdersIdRouteImport
      parentRoute: typeof AccountRoute
    }
    '/api/auth/$': {
      id: '/api/auth/$'
      path: '/api/auth/$'
      fullPath: '/api/auth/$'
      preLoaderRoute: typeof ApiAuthSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface AccountRouteChildren {
  AccountIndexRoute: typeof AccountIndexRoute
  AccountOrdersIdRoute: typeof AccountOrdersIdRoute
}

const AccountRouteChildren: AccountRouteChildren = {
  AccountIndexRoute: AccountIndexRoute,
  AccountOrdersIdRoute: AccountOrdersIdRoute,
}

const AccountRouteWithChildren =
  AccountRoute._addFileChildren(AccountRouteChildren)

interface HqRouteChildren {
  HqAssistantsRoute: typeof HqAssistantsRoute
  HqCatalogRoute: typeof HqCatalogRoute
  HqClientsRoute: typeof HqClientsRoute
  HqDemoRoute: typeof HqDemoRoute
  HqInboxRoute: typeof HqInboxRoute
  HqInquiriesRoute: typeof HqInquiriesRoute
  HqLegalRoute: typeof HqLegalRoute
  HqPagesRoute: typeof HqPagesRoute
  HqPaymentsRoute: typeof HqPaymentsRoute
  HqProjectsRoute: typeof HqProjectsRoute
  HqQualityRoute: typeof HqQualityRoute
  HqTeamRoute: typeof HqTeamRoute
  HqIndexRoute: typeof HqIndexRoute
}

const HqRouteChildren: HqRouteChildren = {
  HqAssistantsRoute: HqAssistantsRoute,
  HqCatalogRoute: HqCatalogRoute,
  HqClientsRoute: HqClientsRoute,
  HqDemoRoute: HqDemoRoute,
  HqInboxRoute: HqInboxRoute,
  HqInquiriesRoute: HqInquiriesRoute,
  HqLegalRoute: HqLegalRoute,
  HqPagesRoute: HqPagesRoute,
  HqPaymentsRoute: HqPaymentsRoute,
  HqProjectsRoute: HqProjectsRoute,
  HqQualityRoute: HqQualityRoute,
  HqTeamRoute: HqTeamRoute,
  HqIndexRoute: HqIndexRoute,
}

const HqRouteWithChildren = HqRoute._addFileChildren(HqRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AccountRoute: AccountRouteWithChildren,
  CheckoutRoute: CheckoutRoute,
  HqRoute: HqRouteWithChildren,
  LoginRoute: LoginRoute,
  PackagesRoute: PackagesRoute,
  PrivacyRoute: PrivacyRoute,
  ReceptionistRoute: ReceptionistRoute,
  ServicesRoute: ServicesRoute,
  StartRoute: StartRoute,
  TermsRoute: TermsRoute,
  WorkRoute: WorkRoute,
  DepartmentsIdRoute: DepartmentsIdRoute,
  OffersSlugRoute: OffersSlugRoute,
  OffersIndexRoute: OffersIndexRoute,
  ApiAuthSplatRoute: ApiAuthSplatRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
